/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package advinhaNumero;

/**
 *
 * @author aliso
 */
public class AdvinhaNumero extends javax.swing.JFrame {
    
    int resultado3;
    /**
     * Creates new form AdvinhaNumero
     */
    public AdvinhaNumero() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        lblValor = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        lblResNum = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto.setText("<html>To pensando em um número bem numeroso que seja de 1 a 5.... Manda aí teu chute sinistroso...</html>");
        lblTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 300, 230));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 281, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Valor: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        btnPalpite.setText("Palpitada");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 140, 50));
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 60, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/advinhaNumero/imagem/balao1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        lblResNum.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblResNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 70, 30));

        lblNum.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 30, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/advinhaNumero/imagem/pensativo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        lblNum.setVisible(true);
        double n = 1 + Math.random() * (6-1);
        int numero = Integer.parseInt(lblValor.getValue().toString());
        int valor = (int) n;
        String resp1 = "É, acertou.... Parabáins.";
        String resp2 = "<html>Errou feio... \n Errou rude!</html>";
        
        String resultado = (valor == numero)?resp1:resp2;
        String resultado2 = (resultado == resp2)?"<html>Era o número ":"";
        
        if (resultado==resp2) {
            resultado3 = valor;
        }
        else {
        lblNum.setVisible(false);
        }
        
        lblTexto.setText(resultado);
        lblResNum.setText(resultado2);
        lblNum.setText(Integer.toString(resultado3));
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvinhaNumero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblResNum;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JSpinner lblValor;
    // End of variables declaration//GEN-END:variables
}
